---
- name: Install Dropbox
  aur: name=dropbox user={{ user.name }}
  tags:
    - aur

- name: Install Dropbox CLI
  aur: name=dropbox-cli user={{ user.name }}
  tags:
    - aur

- name: Symlink personal directory
  file: src=/home/{{ user.name }}/Dropbox/personal dest=/home/{{ user.name }}/personal state=link owner={{ user.name }} group={{ user.group }}
